export default {
    ALPHA_UPPER: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
    ALPHA_LOWER: 'abcdefghijklmnopqrstuvwxyz',
    NUMERIC: '1234567890',
    PARENTHESIS: '()',
    SQUARE_BRACKETS: '[]',
    CURLY_BRACES: '{}',
    SINGLE_QUOTE: "'",
    BACKTICK: '`',
    DOUBLE_QUOTE: '"',
    PLUS: '+',
    EQUALS: '=',
    ANGLE_BRACKETS: '<>',
    FORWARD_SLASH: '/',
    BACK_SLASH: '\\',
    DOLLAR_SIGN: '$',
    SEMI_COLON: ';',
    COLON: ':',
    QUESTION_MARK: '?',
    PERIOD: '.',
    OTHER_SPECIAL: '~!@#%^&*-_=|,'
}